/// Morphological characteristics schema for fungal species prediction.
///
/// This file is auto-generated from the ML training data and must be
/// kept in sync with `model/src/ml/morphology_endpoint_schema.json`.
/// The exact capitalization, spacing, and ordering of all values is canonical.
/// Do NOT modify these values — they are used at both train-time and inference-time.

class MorphologySchema {
  /// All 6 fungal species covered by the training data.
  static const List<String> species = [
    "Alternaria_spp",
    "Aspergillus_section_Flavi",
    "Aspergillus_section_Nigri",
    "Fusarium_spp",
    "Penicillium_spp",
    "Rhizopus_spp",
  ];

  /// Complete morphological characteristics schema.
  /// Field names (keys) have exact capitalization with underscores.
  /// Values are the canonical clean forms from training CSVs.
  static const Map<String, List<String>> characteristics = {
    "Hyphae_Presence": [
      "Cannot Assess Clearly",
      "No",
      "Yes",
    ],
    "Hyphae_Septation": [
      "Aseptate",
      "Aseptate/Coenocytic",
      "Cannot Assess Clearly",
      "No",
      "Septate",
    ],
    "Vesicle_Presence": [
      "Cannot Assess Clearly",
      "No",
      "Yes",
    ],
    "Sporangium_Presence": [
      "Cannot Assess Clearly",
      "No",
      "Yes",
    ],
    "Hyphae_Pigmentation": [
      "Brown/Dark",
      "Cannot Assess Clearly",
      "Dark Brown",
      "Dark Brown/Black",
      "Dark Brown/Green",
      "Dematiaceous",
      "Green",
      "Green/Brown",
      "Green/Yellow",
      "Hyaline",
      "Hyaline to Brown",
      "Hyaline to Dark Brown",
      "Hyaline to Light Brown",
      "Hyaline to Pale Blue/Brown",
      "Hyaline to Pale Brown",
      "Hyaline to Pale Green",
      "Hyaline to Pale Yellow/Brown",
      "Pale Brown/Green",
      "Pale Green/Blue",
      "Pale Green/Brown",
      "Pale Yellow/Green",
    ],
    "Rhizoid_Presence": [
      "Cannot Assess",
      "Cannot Assess Clearly",
      "No",
      "Yes",
    ],
    "Spore_Shape": [
      "Cannot Assess Clearly",
      "Canoe/Sickle-shaped",
      "Canoe/Sickle-shaped and Ovoid/Elliptical",
      "Fusiform/Segmented",
      "Fusiform/Sickle-shaped",
      "Globose",
      "Globose to Barrel-shaped",
      "Globose to Ovoid",
      "Globose to Ovoid/Elliptical",
      "Globose to Subglobose",
      "Muriform/Club-shaped",
      "Muriform/Obclavate",
      "Oval with Septa",
      "Oval/Elongated with Septa",
      "Oval/Muriform",
      "Oval/Muriform/Segmented",
      "Oval/Segmented",
      "Oval/Spherical with Septa",
      "Ovoid to Barrel-shaped",
      "Ovoid/Elliptical",
      "Sickle/Banana-shaped",
      "Spherical",
      "Spherical to Oval",
      "Spherical/Oval",
      "Spherical/Round",
    ],
    "Conidiophore_Branching": [
      "Absent",
      "Biverticillate/Branched",
      "Branched",
      "Cannot Assess Clearly",
      "Simple",
      "Simple to Slightly Branched",
      "Simple/Branched",
      "Simple/Variable",
      "Unbranched",
    ],
    "Phialide_Arrangement": [
      "Absent",
      "Biseriate",
      "Brush-like",
      "Cannot Assess Clearly",
      "Metulae and Phialides",
      "Phialides in Clusters",
      "Phialides on Conidiophores",
      "Present",
      "Radial",
      "Terminal",
    ],
    "Spore_Arrangement": [
      "Absent",
      "Cannot Assess Clearly",
      "Chained/Segmented",
      "Chains",
      "Chains and Clusters",
      "Chains/Branched",
      "Chains/Clustered",
      "Chains/Clusters",
      "Chains/Scattered",
      "Clustered",
      "Clustered Head",
      "Clustered Head / Radiate",
      "Clustered/Attached",
      "Clustered/Fragmented",
      "Clustered/Loose",
      "Clustered/Massed",
      "Clustered/Scattered",
      "Clusters",
      "Clusters/Short Chains",
      "Columnar/Radiate",
      "Fragmented/Chains",
      "In Sporangium",
      "Long Chains",
      "Massed",
      "Radial Columns",
      "Radiate",
      "Radiate/Chains from Vesicle",
      "Radiate/Clustered",
      "Radiate/Columnar",
      "Radiate/Dispersed",
      "Radiate/Loose",
      "Radiate/Scattered",
      "Scattered/Clustered",
      "Scattered/Dispersed",
      "Scattered/Free Conidia",
      "Scattered/Free Conidia and Clustered/Sclerotium",
      "Scattered/Loose",
      "Scattered/Massed",
      "Short Chains/Clusters",
      "Single/Scattered",
      "Single/Short Chains",
      "Within Sporangium",
    ],
    "Spore_Color": [
      "Blue",
      "Blue-Green",
      "Blue-green/Green",
      "Blue/Green",
      "Blue/Yellow",
      "Brown/Black",
      "Brown/Dark",
      "Brown/Dark Brown",
      "Cannot Assess Clearly",
      "Dark Blue",
      "Dark Blue/Brown",
      "Dark Brown to Black",
      "Dark Brown/Black",
      "Dark Brown/Green",
      "Dark Green/Blue",
      "Dark Green/Brown",
      "Green",
      "Green/Blue",
      "Green/Brown",
      "Green/Dark",
      "Green/Yellow",
      "Greenish-Blue",
      "Greenish-Brown",
      "Hyaline",
      "Hyaline to Light Brown",
      "Hyaline to Pale",
      "Hyaline to Pale Green",
      "Hyaline/Light Brown",
      "Yellow/Brown",
    ],
    "Sporangiophore_Presence": [
      "Absent",
      "Cannot Assess Clearly",
      "No",
      "Yes",
    ],
    "Hyphae_Branching": [
      "Acute-angle",
      "Acute-angle/Variable",
      "Cannot Assess Clearly",
      "Irregular",
      "No",
      "Right-angle/Irregular",
      "Yes",
    ],
    "Hyphae_Width": [
      "Broad",
      "Cannot Assess Clearly",
      "Medium",
      "Medium to Wide",
      "Narrow",
      "Narrow to Medium",
      "Narrow-Medium",
      "Thin",
      "Thin to Medium",
      "Wide",
      "Wide/Broad",
    ],
    "Columella_Presence": [
      "Cannot Assess",
      "Cannot Assess Clearly",
      "No",
      "Possibly Present",
      "Yes",
    ],
    "Spore_Type": [
      "Arthroconidia/Chlamydospores",
      "Cannot Assess Clearly",
      "Chlamydospores/Sexual Spores",
      "Conidia",
      "Conidia and Other",
      "Conidia and Sclerotium",
      "Conidia/Hyphal Fragments",
      "Hyphal Fragments",
      "Hyphal Fragments/Arthroconidia",
      "Macroconidia",
      "Macroconidia and Microconidia",
      "Muriform/Segmented Conidia",
      "Other",
      "Sporangiospores",
    ],
    "Conidiophore_Length": [
      "Absent",
      "Cannot Assess Clearly",
      "Long",
      "Medium",
      "Medium to Long",
      "Medium-Long",
      "Short",
      "Short-Medium",
    ],
    "Conidiophore_Surface": [
      "Cannot Assess Clearly",
      "Rough",
      "Rough/Coiled",
      "Rough/Spiny",
      "Smooth",
      "Smooth to Rough",
    ],
    "Vesicle_Shape": [
      "Absent",
      "Cannot Assess Clearly",
      "Clavate to Globose",
      "Globose",
      "Globose to Subglobose",
      "Globose/Elongated",
      "Globose/Ovoid",
      "Spherical/Hemispherical",
    ],
    "Conidiophore_Presence": [
      "Cannot Assess Clearly",
      "Likely Yes",
      "No",
      "Present",
      "Yes",
    ],
    "Spore_Surface": [
      "Cannot Assess Clearly",
      "Rough",
      "Rough/Thick-walled",
      "Rough/Verrucose",
      "Rough/Warty",
      "Smooth",
      "Smooth to Rough",
      "Smooth to Slightly Rough",
      "Smooth/Thick-walled",
    ],
    "Sterigmata_Arrangement": [
      "Absent",
      "Cannot Assess Clearly",
      "Phialides in Clusters/Simple",
      "Radiate/Covering entire vesicle",
      "Radiate/Covering upper 3/4 of vesicle",
      "Verticillate/Penicillate",
    ],
  };

  /// Get all valid values for a given characteristic field.
  /// Returns null if the field does not exist.
  static List<String>? getValidValues(String fieldName) {
    return characteristics[fieldName];
  }

  /// Check if a value is valid for a given characteristic field.
  static bool isValidValue(String fieldName, String value) {
    final validValues = characteristics[fieldName];
    return validValues != null && validValues.contains(value);
  }

  /// Get all 22 characteristic field names (in order).
  static List<String> get allFieldNames => characteristics.keys.toList();

  /// Number of morphological characteristic fields.
  static const int fieldCount = 22;
}
